### ISSUE TITLE
Warning about cock

### ISSUE THREAD

**Issue by wasamasa** [klutometis/sicp-chicken#2]
When successfully installing the `sicp` egg, I've noticed a warning about a missing `cock` executable. After a few tries (apparently there is no official documentation what `cock` is supposed to be) I've found out that installing the `cock-utils` egg (which probably installs the `cock` egg, too) allows the installation to run without any important warnings. Perhaps it would be better to add an (optional) dependency on `cock-utils`?

**Comment by klutometis** [comment]
No, thank you; Vasilij!

I needed a little activation energy to finally document the things, and this ticket provided it!
