### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by sjamaan** [klutometis/sicp-chicken#3]
Hi Peter,

You have listed 0.12.3 and 0.12.2 in `sicp.release-info`, but they do not have a corresponding tag, which causes errors when fetching these versions.

Check the henrietta-cache error report here: http://code.call-cc.org/henrietta-cache/latest-err-4

**Comment by klutometis** [comment]
Thanks, Peter; is the best things just to delete the entries from `sicp.release-info` and tag a new release?

**Comment by sjamaan** [comment]
It truly does not matter: you can either remove the entries (no need to tag a new release), or just add the missing tags retroactively (if you remember which changesets they were supposed to go on).

The only thing you _shouldn't_ do its move tags after they've been published.

**Comment by klutometis** [comment]
Ok; thanks, Peter! [Done](https://github.com/klutometis/sicp-chicken/commit/249660780647f2c10664ff20ab8ec24573e2c596).
